"""Domain logic for text processing and voice handling."""

from .normalization import (
    TextNormalizer,
    digits_to_words,
    normalize_numbers,
    normalize_times,
    number_to_words_0_59,
    number_to_words_0_99,
    number_to_words_0_999,
    number_to_words_0_9999,
    ordinal_to_words,
    ordinalize_words,
    time_to_words,
)
from .morphology import analyze_english_text
from .expressions import extract_english_expressions
from .splitting import smart_split, split_parts, split_sentences
from .style import (
    DEFAULT_STYLE_PRESET,
    PIPELINE_STYLE_PARAM_NAMES,
    STYLE_PRESET_CHOICES,
    normalize_style_preset,
    resolve_style_runtime,
)
from .voice import (
    CHOICES,
    DEFAULT_VOICE,
    LANGUAGE_CHOICES,
    LANGUAGE_LABELS,
    available_language_codes,
    default_voice_for_lang,
    get_voice_choices,
    limit_dialogue_parts,
    normalize_lang_code,
    normalize_voice_input,
    normalize_voice_tag,
    parse_voice_segments,
    register_runtime_language,
    register_runtime_voices,
    resolve_voice,
    summarize_voice,
    voice_language,
)

__all__ = [
    "CHOICES",
    "DEFAULT_VOICE",
    "LANGUAGE_CHOICES",
    "LANGUAGE_LABELS",
    "available_language_codes",
    "TextNormalizer",
    "DEFAULT_STYLE_PRESET",
    "default_voice_for_lang",
    "digits_to_words",
    "get_voice_choices",
    "limit_dialogue_parts",
    "analyze_english_text",
    "extract_english_expressions",
    "normalize_lang_code",
    "normalize_numbers",
    "normalize_style_preset",
    "normalize_times",
    "normalize_voice_input",
    "normalize_voice_tag",
    "number_to_words_0_59",
    "number_to_words_0_99",
    "number_to_words_0_999",
    "number_to_words_0_9999",
    "ordinal_to_words",
    "ordinalize_words",
    "parse_voice_segments",
    "PIPELINE_STYLE_PARAM_NAMES",
    "register_runtime_language",
    "register_runtime_voices",
    "resolve_voice",
    "resolve_style_runtime",
    "smart_split",
    "STYLE_PRESET_CHOICES",
    "split_parts",
    "split_sentences",
    "summarize_voice",
    "time_to_words",
    "voice_language",
]
